apiVersion: kustomize.toolkit.fluxcd/io/v1
kind: Kustomization
metadata:
  name: external-secrets-crd
  namespace: flux-system
spec:
  interval: 10m
  path: ./deploy/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-secrets
