apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://kv-jellyhomelabprod.vault.azure.net/
      tenantId: "3c78a8ad-6f4f-45a0-bec9-8538f870a693"
      serviceAccountRef:
        name: azure-kv-store-reader
        namespace: external-secrets
