apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airflow-prod-cert
  namespace: airflow-prod
spec:
  secretName: airflow-prod-cert-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - airflow-prod.jellylabs.xyz