apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/airflow
- configmap.yaml
- salesforce-externalsecret.yaml
- warehouse-externalsecret.yaml
- certificate.yaml

patchesStrategicMerge:
- release-patch.yaml