apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  targetNamespace: airflow-prod
  values:
    airflow:
      extraEnvFrom:
        - secretRef:
            name: salesforce-credentials
        - secretRef:
            name: warehouse-db-credentials
        - configMapRef:
            name: warehouse-db-config
    
    webserver:
      ingress:
        web:
          hosts:
            - name: airflow-prod.jellylabs.xyz
              tls:
                enabled: true
                secretName: airflow-prod-cert-secret