apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: salesforce-credentials
  namespace: airflow-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: salesforce-credentials
    creationPolicy: Owner
  data:
  - secretKey: SALESFORCE_USERNAME
    remoteRef:
      key: salesforce-username-prod
  - secretKey: SALESFORCE_PASSWORD
    remoteRef:
      key: salesforce-password-prod
  - secretKey: SALESFORCE_SECURITY_TOKEN
    remoteRef:
      key: salesforce-security-token-prod
  - secretKey: SALESFORCE_DOMAIN
    remoteRef:
      key: salesforce-domain-prod