apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: salesforce-credentials
  namespace: airflow-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: salesforce-credentials
    creationPolicy: Owner
  data:
  - secretKey: SALESFORCE_PASSWORD
    remoteRef:
      key: app--salesforce-password--prod
  - secretKey: SALESFORCE_SECURITY_TOKEN
    remoteRef:
      key: app--salesforce-cjelly-securitytoken--prod
  - secretKey: SALESFORCE_CONSUMER_KEY
    remoteRef:
      key: app--salesforce-consumer-key--prod
  - secretKey: SALESFORCE_CONSUMER_SECRET
    remoteRef:
      key: app--salesforce-consumer-secret--prod