apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: warehouse-db-credentials
  namespace: airflow-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: warehouse-db-credentials
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: warehouse-db-app-password