apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actualbudget-backup-secrets
  namespace: actualbudget
  labels:
    app.kubernetes.io/name: actualbudget
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: homelab
spec:
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: actualbudget-backup-secrets
    creationPolicy: Owner
  data:
    - secretKey: AZURE_STORAGE_CONNECTION_STRING
      remoteRef:
        key: secret/actualbudget-backup-connection-string
