apiVersion: v1
kind: ServiceAccount
metadata:
  name: actualbudget-backup
  namespace: actualbudget
  labels:
    app.kubernetes.io/name: actualbudget
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: homelab
  annotations:
    azure.workload.identity/client-id: daba911e-7994-43b0-8e64-c84317feb54f
