apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airflow-cert
  namespace: airflow
spec:
  secretName: airflow-cert-secret
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  dnsNames:
  - airflow.jellylabs.xyz