apiVersion: v1
kind: ConfigMap
metadata:
  name: warehouse-db-config-dev
  namespace: airflow
data:
  POSTGRES_HOST_DEV: "warehouse-db-dev-cnpg-v1-rw.warehouse-dev.svc.cluster.local"
  POSTGRES_DATABASE_DEV: "app"
  POSTGRES_USER_DEV: "app"
  POSTGRES_PORT_DEV: "5432"