apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kubernetes-secret-store-airflow
  namespace: airflow
spec:
  provider:
    kubernetes:
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-database-connection
  namespace: airflow
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/instance: airflow-database-connection
    app.kubernetes.io/part-of: homelab
spec:
  secretStoreRef:
    name: kubernetes-secret-store-airflow
    kind: SecretStore
  target:
    name: airflow-metadata
    creationPolicy: Owner
  data:
  - secretKey: connection
    remoteRef:
      key: airflow-db-production-cnpg-v1-app
      property: uri