apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

resources:
- ../../base/airflow
- configmap-prod.yaml
- configmap-dev.yaml
- salesforce-externalsecret-prod.yaml
- salesforce-externalsecret-dev.yaml
- warehouse-externalsecret-prod.yaml
- warehouse-externalsecret-dev.yaml
- certificate.yaml

patches:
- path: release-patch.yaml
  target:
    kind: HelmRelease
    name: airflow

replacements:
- source:
    kind: Secret
    name: airflow-db-production-cnpg-v1-app
    fieldPath: data.user
  targets:
  - select:
      kind: HelmRelease
      name: airflow
    fieldPaths:
    - spec.values.data.metadataConnection.user
- source:
    kind: Secret
    name: airflow-db-production-cnpg-v1-app
    fieldPath: data.password
  targets:
  - select:
      kind: HelmRelease
      name: airflow
    fieldPaths:
    - spec.values.data.metadataConnection.pass
- source:
    kind: Secret
    name: airflow-db-production-cnpg-v1-app
    fieldPath: data.host
  targets:
  - select:
      kind: HelmRelease
      name: airflow
    fieldPaths:
    - spec.values.data.metadataConnection.host
- source:
    kind: Secret
    name: airflow-db-production-cnpg-v1-app
    fieldPath: data.dbname
  targets:
  - select:
      kind: HelmRelease
      name: airflow
    fieldPaths:
    - spec.values.data.metadataConnection.db