apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

resources:
- ../../base/airflow
- configmap-prod.yaml
- configmap-dev.yaml
- salesforce-externalsecret-prod.yaml
- salesforce-externalsecret-dev.yaml
- warehouse-externalsecret-prod.yaml
- warehouse-externalsecret-dev.yaml
- certificate.yaml
- database-externalsecret.yaml

patches:
- path: release-patch.yaml
  target:
    kind: HelmRelease
    name: airflow

