apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  values:
    airflow:
      extraEnvFrom:
        - secretRef:
            name: salesforce-credentials-prod
        - secretRef:
            name: salesforce-credentials-dev
        - secretRef:
            name: warehouse-db-credentials-prod
        - secretRef:
            name: warehouse-db-credentials-dev
        - configMapRef:
            name: warehouse-db-config-prod
        - configMapRef:
            name: warehouse-db-config-dev
    
    ingress:
      web:
        hosts:
          - name: airflow.jellylabs.xyz
            tls:
              enabled: true
              secretName: airflow-cert-secret