apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: salesforce-credentials-prod
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: salesforce-credentials-prod
    creationPolicy: Owner
  data:
  - secretKey: SALESFORCE_PASSWORD_PROD
    remoteRef:
      key: app--salesforce-password--prod
  - secretKey: SALESFORCE_SECURITY_TOKEN_PROD
    remoteRef:
      key: app--salesforce-cjelly-securitytoken--prod
  - secretKey: SALESFORCE_CONSUMER_KEY_PROD
    remoteRef:
      key: app--salesforce-consumer-key--prod
  - secretKey: SALESFORCE_CONSUMER_SECRET_PROD
    remoteRef:
      key: app--salesforce-consumer-secret--prod