apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: salesforce-credentials-dev
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: salesforce-credentials-dev
    creationPolicy: Owner
  data:
  - secretKey: SALESFORCE_PASSWORD_DEV
    remoteRef:
      key: app--salesforce-password--dev
  - secretKey: SALESFORCE_SECURITY_TOKEN_DEV
    remoteRef:
      key: app--salesforce-cjelly-securitytoken--dev
  - secretKey: SALESFORCE_CONSUMER_KEY_DEV
    remoteRef:
      key: app--salesforce-consumer-key--dev
  - secretKey: SALESFORCE_CONSUMER_SECRET_DEV
    remoteRef:
      key: app--salesforce-consumer-secret--dev