apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warehouse-db-credentials-dev
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: warehouse-db-credentials-dev
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_PASSWORD_DEV
    remoteRef:
      key: app--warehouse-postgres-password--dev