apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warehouse-db-credentials-prod
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: warehouse-db-credentials-prod
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_PASSWORD_PROD
    remoteRef:
      key: app--warehouse-postgres-password--prod