apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: audiobookshelf-secrets
  namespace: audiobookshelf
spec:
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: audiobookshelf-secrets
    creationPolicy: Owner
  data:
    - secretKey: audiobookshelf-cloudflare-tunnel-credentials
      remoteRef:
        key: secret/cf-tunnel-creds
