apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shared-cloudflare-edge-secrets
spec:
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: shared-cloudflare-edge-secrets
    creationPolicy: Owner
  data:
    - secretKey: tunnel-credentials
      remoteRef:
        key: secret/cf-tunnel-creds
