apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
  labels:
    app: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 1000 # default node
        runAsUser: 1000
        runAsGroup: 1000

      containers:
      - name: audiobookshelf
        image: ghcr.io/advplyr/audiobookshelf:2.24.0
        ports:
          - containerPort: 3005
        envFrom:
          - configMapRef:
              name: audiobookshelf-config
        volumeMounts:
          - name: audiobookshelf-config-pvc
            mountPath: /config
          - name: audiobookshelf-podcasts-pvc
            mountPath: /podcasts
          - name: audiobookshelf-metadata-pvc
            mountPath: /metadata
          - name: audiobookshelf-audiobooks-pvc
            mountPath: /audiobooks
      volumes:
        - name: audiobookshelf-config-pvc
          persistentVolumeClaim:
            claimName: audiobookshelf-config-pvc
        - name: audiobookshelf-podcasts-pvc
          persistentVolumeClaim:
            claimName: audiobookshelf-podcasts-pvc
        - name: audiobookshelf-metadata-pvc
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata-pvc
        - name: audiobookshelf-audiobooks-pvc
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks-pvc