apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: audiobookshelf
  name: audiobookshelf-audiobooks-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: audiobookshelf
  name: audiobookshelf-podcasts-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: audiobookshelf
  name: audiobookshelf-config-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: audiobookshelf
  name: audiobookshelf-metadata-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce