# SecretStore for accessing Kubernetes secrets within the same namespace
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kubernetes-local
  namespace: airflow
spec:
  provider:
    kubernetes:
      # Specify the namespace to read secrets from
      remoteNamespace: airflow
      # Reference the service account for accessing secrets
      auth:
        serviceAccount:
          name: external-secrets-kubernetes-reader
---
# ServiceAccount for External Secrets to read Kubernetes secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-kubernetes-reader
  namespace: airflow
---
# Role allowing External Secrets to read secrets (includes required selfsubjectrulesreviews permission)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-kubernetes-reader
  namespace: airflow
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["selfsubjectrulesreviews"]
  verbs: ["create"]
---
# RoleBinding for the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-kubernetes-reader
  namespace: airflow
subjects:
- kind: ServiceAccount
  name: external-secrets-kubernetes-reader
  namespace: airflow
roleRef:
  kind: Role
  name: external-secrets-kubernetes-reader
  apiGroup: rbac.authorization.k8s.io
---
# ExternalSecret that syncs the uri field from CNPG secret to connection field
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-metadata-connection
  namespace: airflow
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/instance: airflow-metadata-connection
    app.kubernetes.io/part-of: homelab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-local
    kind: SecretStore
  target:
    name: airflow-metadata-connection
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: connection
      remoteRef:
        key: airflow-db-production-cnpg-v1-app
        property: uri
