apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-admin-credentials
  namespace: airflow
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/instance: airflow-admin-credentials
    app.kubernetes.io/part-of: homelab
spec:
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: airflow-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: _AIRFLOW_WWW_USER_USERNAME
      remoteRef:
        key: secret/airflow-admin-username
    - secretKey: _AIRFLOW_WWW_USER_PASSWORD
      remoteRef:
        key: secret/airflow-admin-password
    - secretKey: _AIRFLOW_WWW_USER_EMAIL
      remoteRef:
        key: secret/airflow-admin-email
    - secretKey: _AIRFLOW_WWW_USER_FIRSTNAME
      remoteRef:
        key: secret/airflow-admin-firstname
    - secretKey: _AIRFLOW_WWW_USER_LASTNAME
      remoteRef:
        key: secret/airflow-admin-lastname