apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  releaseName: airflow
  targetNamespace: airflow
  interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: airflow
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: airflow
        namespace: flux-system
  values:
    # Use LocalExecutor since we're on a single-node cluster
    executor: LocalExecutor
    
    # Airflow configuration
    airflow:
      config:
        AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
        AIRFLOW__CORE__LOAD_EXAMPLES: "false"
        AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
        AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
        AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"
      
    # Database configuration for CloudNative-PG
    postgresql:
      enabled: false
    
    data:
      metadataConnection:
        user:
          valueFrom:
            secretKeyRef:
              name: airflow-db-production-cnpg-v1-app
              key: user
        pass:
          valueFrom:
            secretKeyRef:
              name: airflow-db-production-cnpg-v1-app
              key: password
        protocol: postgresql
        host:
          valueFrom:
            secretKeyRef:
              name: airflow-db-production-cnpg-v1-app
              key: host
        port:
          valueFrom:
            secretKeyRef:
              name: airflow-db-production-cnpg-v1-app
              key: port
        db:
          valueFrom:
            secretKeyRef:
              name: airflow-db-production-cnpg-v1-app
              key: dbname
        sslmode: disable

    # Git-sync configuration for DAGs
    dags:
      gitSync:
        enabled: true
        repo: https://github.com/chris-jelly/de-airflow-pipeline
        branch: main
        subPath: "dags"
        wait: 60
        containerName: git-sync
        uid: 65533
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m

    # Resource configuration
    scheduler:
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 1Gi
          cpu: 1000m

    # Ingress configuration at top level
    ingress:
      web:
        enabled: true
        ingressClassName: traefik
        hosts:
          - name: airflow.jellylabs.xyz
            tls:
              enabled: true
              secretName: airflow-cert-secret
    
    # Inject secrets via environment variables
    extraEnvFrom: |
      - secretRef:
          name: airflow-admin-credentials
    
    webserver:
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 1Gi
          cpu: 1000m
      
      # Default admin user disabled - will be created via environment variables
      defaultUser:
        enabled: false

    # GitOps compatibility - disable Helm hooks for jobs
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false

    # Disable components we don't need for single-node setup
    workers:
      replicas: 0
    
    flower:
      enabled: false
    
    redis:
      enabled: false
    
    pgbouncer:
      enabled: false