apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  releaseName: airflow
  targetNamespace: airflow
  interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: airflow
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: airflow
        namespace: flux-system
  values:
    # Use KubernetesExecutor to run tasks as individual pods
    executor: KubernetesExecutor

    # Airflow configuration
    airflow:
      config:
        AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
        AIRFLOW__CORE__LOAD_EXAMPLES: "false"
        AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
        AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
        AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"
        # KubernetesExecutor configuration
        AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
        AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
        AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE: "False"
        AIRFLOW__KUBERNETES__WORKER_PODS_CREATION_BATCH_SIZE: "5"
      
    # Database configuration for CloudNative-PG
    postgresql:
      enabled: false
    
    data:
      metadataSecretName: airflow-metadata-connection

    # Git-sync configuration for DAGs
    dags:
      gitSync:
        enabled: true
        repo: https://github.com/chris-jelly/de-airflow-pipeline
        branch: main
        subPath: "dags"
        wait: 60
        containerName: git-sync
        uid: 65533
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m

    # Resource configuration
    scheduler:
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 1Gi
          cpu: 1000m

    # Ingress configuration at top level
    ingress:
      web:
        enabled: true
        ingressClassName: traefik
        hosts:
          - name: airflow.jellylabs.xyz
            tls:
              enabled: true
              secretName: airflow-cert-secret

    webserver:
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 1Gi
          cpu: 1000m
      
      # Default admin user disabled - will be created via environment variables
      defaultUser:
        enabled: false

    # GitOps compatibility - disable Helm hooks for jobs
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: true
    
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false

    # KubernetesExecutor worker pod defaults
    workers:
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 1Gi
          cpu: 1000m
      persistence:
        enabled: false  # Not needed with git-sync

    # Disable components we don't need
    flower:
      enabled: false

    redis:
      enabled: false

    pgbouncer:
      enabled: false