apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  releaseName: airflow
  targetNamespace: airflow
  interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: airflow
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: airflow
        namespace: flux-system
  values:
    # Use KubernetesExecutor to run tasks as individual pods
    executor: KubernetesExecutor

    # Airflow configuration
    airflow:
      config:
        AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
        AIRFLOW__CORE__LOAD_EXAMPLES: "false"
        AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"
        # KubernetesExecutor configuration
        AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE: "airflow"
        AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS: "true"
        AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS_ON_FAILURE: "False"
        AIRFLOW__KUBERNETES_EXECUTOR__WORKER_PODS_CREATION_BATCH_SIZE: "5"

    # Database configuration for CloudNative-PG
    postgresql:
      enabled: false

    data:
      metadataSecretName: airflow-metadata-connection

    # Git-sync configuration for DAGs
    dags:
      gitSync:
        enabled: true
        repo: https://github.com/chris-jelly/de-airflow-pipeline
        branch: main
        subPath: "dags"
        wait: 60
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m

    # Resource configuration
    scheduler:
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 1Gi
          cpu: 1000m

    # Airflow 3: API server replaces webserver
    apiServer:
      resources:
        requests:
          memory: 1Gi
          cpu: 200m
        limits:
          memory: 2Gi
          cpu: 1000m

    # Ingress configuration for Airflow 3 API server
    ingress:
      apiServer:
        enabled: true
        ingressClassName: traefik
        hosts:
          - name: airflow.jellylabs.xyz
            tls:
              enabled: true
              secretName: airflow-cert-secret

    # Inject secrets via environment variables
    extraEnvFrom: |
      - secretRef:
          name: airflow-admin-credentials

    # GitOps compatibility - disable Helm hooks for jobs
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: true
      defaultUser:
        enabled: true
      # Override default args to read credentials from env vars injected
      # via extraEnvFrom (airflow-admin-credentials secret) instead of
      # hardcoded chart defaults
      args:
        - "bash"
        - "-c"
        - |-
          exec \
          airflow users create \
            -r Admin \
            -u "${_AIRFLOW_WWW_USER_USERNAME}" \
            -e "${_AIRFLOW_WWW_USER_EMAIL}" \
            -f "${_AIRFLOW_WWW_USER_FIRSTNAME}" \
            -l "${_AIRFLOW_WWW_USER_LASTNAME}" \
            -p "${_AIRFLOW_WWW_USER_PASSWORD}"

    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: true

    # KubernetesExecutor worker pod defaults
    workers:
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 1Gi
          cpu: 1000m
      persistence:
        enabled: false # Not needed with git-sync

    # Disable components we don't need
    flower:
      enabled: false

    redis:
      enabled: false

    pgbouncer:
      enabled: false
