apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-secrets
  namespace: linkding
spec:
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: linkding-secrets
    creationPolicy: Owner
  data:
  - secretKey: LD_DB_PASSWORD
    remoteRef:
      key: secret/linkding-db-password
  - secretKey: LD_DB_USERNAME
    remoteRef:
      key: secret/linkding-db-username
  - secretKey: LD_SUPERUSER_NAME
    remoteRef:
      key: secret/linkding-superuser-name
  - secretKey: LD_SUPERUSER_PASSWORD
    remoteRef:
      key: secret/linkding-superuser-password
  - secretKey: linkding-cloudflare-tunnel-credentials
    remoteRef:
      key: secret/cf-tunnel-creds
