apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: actualbudget-cert
  namespace: actualbudget
spec:
  secretName: actualbudget-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  dnsNames:
  - actualbudget.jellylabs.xyz