apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sales-pipeline-pulse-secrets
  namespace: streamlit
  labels:
    app.kubernetes.io/name: sales-pipeline-pulse
    app.kubernetes.io/instance: sales-pipeline-pulse
    app.kubernetes.io/part-of: homelab
spec:
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: sales-pipeline-pulse-secrets
    creationPolicy: Owner
  data:
    - secretKey: SALES_WAREHOUSE_URL
      remoteRef:
        key: secret/sales-warehouse-url
