apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airflow-dev-cert
  namespace: airflow-dev
spec:
  secretName: airflow-dev-cert-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - airflow-dev.jellylabs.xyz