apiVersion: v1
kind: ConfigMap
metadata:
  name: warehouse-db-config
  namespace: airflow-dev
data:
  POSTGRES_HOST: "warehouse-db-dev-cnpg-v1-rw.warehouse-dev.svc.cluster.local"
  POSTGRES_DATABASE: "app"
  POSTGRES_USER: "app"
  POSTGRES_PORT: "5432"