apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow-dev

resources:
- ../../base/airflow
- configmap.yaml
- salesforce-externalsecret.yaml
- warehouse-externalsecret.yaml
- certificate.yaml

patches:
- path: release-patch.yaml
  target:
    kind: HelmRelease
    name: airflow