apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow-dev
  namespace: airflow-dev
spec:
  targetNamespace: airflow-dev
  values:
    airflow:
      extraEnvFrom:
        - secretRef:
            name: salesforce-credentials
        - secretRef:
            name: warehouse-db-credentials
        - configMapRef:
            name: warehouse-db-config
    
    webserver:
      ingress:
        web:
          hosts:
            - name: airflow-dev.jellylabs.xyz
              tls:
                enabled: true
                secretName: airflow-dev-cert-secret