apiVersion: v1
kind: ServiceAccount
metadata:
  name: mealie-backup
  namespace: mealie
  labels:
    app.kubernetes.io/name: mealie
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: homelab
  annotations:
    azure.workload.identity/client-id: b5770047-281b-400e-9275-9cf9580654df
