apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-backup-config
  namespace: mealie
  labels:
    app.kubernetes.io/name: mealie
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: homelab
data:
  CONTAINER_NAME: "mealie-backups"
  BACKUP_RETENTION_COUNT: "8"
  BACKUP_PREFIX: "mealie-app-data-backup"
