apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-backup-config
  namespace: mealie
  labels:
    app.kubernetes.io/name: mealie
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: homelab
data:
  AZCOPY_AUTO_LOGIN_TYPE: "WORKLOAD"
  AZCOPY_JOB_PLAN_LOCATION: "/tmp/azcopy-plans"
  BACKUP_PREFIX: "mealie-app-data-backup"
  BACKUP_DESTINATION_URL: "https://sthomelabbackups.blob.core.windows.net/mealie/files"
  AZCOPY_LOG_LOCATION: "/tmp/azcopy-logs"
