apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
resources:
  - ../../base/mealie
  - externalsecret.yaml
  - ingress.yaml
  - certificate.yaml
  - backup-config-configmap.yaml
  - backup-script-configmap.yaml
  - backup-externalsecret.yaml
  - backup-cronjob.yaml
