apiVersion: v1
kind: Namespace
metadata:
  name: streamlit
  labels:
    app.kubernetes.io/name: sales-pipeline-pulse
    app.kubernetes.io/instance: sales-pipeline-pulse
    app.kubernetes.io/part-of: homelab
