apiVersion: v1
kind: Service
metadata:
  name: sales-pipeline-pulse
  namespace: streamlit
  labels:
    app.kubernetes.io/name: sales-pipeline-pulse
    app.kubernetes.io/instance: sales-pipeline-pulse
    app.kubernetes.io/part-of: homelab
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8501
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: sales-pipeline-pulse
    app.kubernetes.io/instance: sales-pipeline-pulse
