apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cloudnative-pg
spec:
  releaseName: cnpg
  targetNamespace: cloudnative-pg
  interval: 10m
  chart:
    spec:
      chart: cloudnative-pg
      version: 1.26.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  values:
    crds:
      enabled: true
      keep: true 