apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cloudnative-pg
spec:
  releaseName: cloudnative-pg
  targetNamespace: cloudnative-pg
  interval: 10m
  chart:
    spec:
      chart: cloudnative-pg
      version: 1.22.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  values:
    crds:
      enabled: true
      keep: true 