apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 24h
  url: https://raw.githubusercontent.com/cloudnative-pg/charts/main 