apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
  namespace: actualbudget
spec:
  releaseName: actualbudget
  targetNamespace: actualbudget
  interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: actualbudget
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
  values:
    # Resource configuration
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 500m

    # Persistence configuration
    persistence:
      enabled: true
      size: 20Gi
      storageClass: ""
      accessModes:
        - ReadWriteOnce

    # Security configuration
    podSecurityContext:
      fsGroup: 1001
      fsGroupChangePolicy: "OnRootMismatch"
    
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      privileged: false
      runAsUser: 1001
      runAsGroup: 1001

    # Service configuration (internal only)
    service:
      type: ClusterIP
      port: 5006

    # Ingress configuration
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: actualbudget.jellylabs.xyz
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: actualbudget-tls
          hosts:
            - actualbudget.jellylabs.xyz

