apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
    template:
      data:
        host: "warehouse-db-production-cnpg-v1-rw.warehouse.svc.cluster.local"
        database: "app"
        username: "app"
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: app--warehouse-postgres-password--prod
