apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  values:
    ingress:
      web:
        hosts:
          - name: airflow.jellylabs.xyz
            tls:
              enabled: true
              secretName: airflow-cert-secret