apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: salesforce-conn
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-work-integrations-store
    kind: ClusterSecretStore
  target:
    name: salesforce-conn
    creationPolicy: Owner
    template:
      data:
        AIRFLOW_CONN_SALESFORCE: '{"conn_type": "salesforce", "login": "airflow-integration@orgfarm-d58c800d67-dev-ed.develop.my.salesforce.com", "extra": {"consumer_key": "{{ .consumer_key }}", "private_key": "{{ .private_key | replace "\n" "\\n" }}", "domain": "login"}}'
  data:
  - secretKey: consumer_key
    remoteRef:
      key: app--salesforce-consumer-key--prod
  - secretKey: private_key
    remoteRef:
      key: app--salesforce-private-key--prod
