apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warehouse-postgres-conn
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: warehouse-postgres-conn
    creationPolicy: Owner
    template:
      data:
        AIRFLOW_CONN_WAREHOUSE_POSTGRES: "postgresql://app:{{ .password }}@warehouse-db-production-cnpg-v1-rw.warehouse.svc.cluster.local:5432/app"
  data:
  - secretKey: password
    remoteRef:
      key: app--warehouse-postgres-password--prod
