# ExternalSecret that syncs the warehouse CNPG connection URI via cross-namespace
# Kubernetes provider. Uses 30s refresh (in-cluster reads are cheap).
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warehouse-postgres-conn
  namespace: airflow
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: kubernetes-warehouse
    kind: SecretStore
  target:
    name: warehouse-postgres-conn
    creationPolicy: Owner
  data:
    - secretKey: AIRFLOW_CONN_WAREHOUSE_POSTGRES
      remoteRef:
        key: warehouse-db-production-cnpg-v1-app
        property: uri
