# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
  labels:
    app: linkding
spec:
  selector:
    matchLabels:
      app: linkding
  replicas: 1
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        fsGroup: 33 # www-data group ID
        runAsUser: 33
        runAsGroup: 33

      containers:
      - name: linkding
        image: sissbruecker/linkding:1.37.0
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        ports:
        - containerPort: 9090

        envFrom:
          - secretRef:
              name: linkding-secrets
              prefix: LD_

        volumeMounts:
        - name: linkding-data
          mountPath: /etc/linkding/data

        securityContext:
          allowPrivilegeEscalation: false

      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
