# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
  labels:
    app: linkding
spec:
  selector:
    matchLabels:
      app: linkding
  replicas: 1
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
      - name: linkding
        image: sissbruecker/linkding:1.37.0
        ports:
        - containerPort: 9090

        volumeMounts:
        - name: linkding-data
          mountPath: /etc/linkding/data

        securityContext:
          runAsUser: 33
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
