apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: renovate
spec:
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: github-token
    creationPolicy: Owner
  data:
  - secretKey: RENOVATE_TOKEN
    remoteRef:
      key: secret/github-classic-cjelly-allrepos
